# Generated by Django 4.1.3 on 2024-02-28 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='region',
            field=models.CharField(blank=True, choices=[('제주', '제주'), ('전북', '전북'), ('전남', '전남'), ('경기', '경기'), ('인천', '인천'), ('강원', '강원'), ('대전', '대전'), ('울산', '울산'), ('부산', '부산'), ('충북', '충북'), ('경북', '경북'), ('경남', '경남'), ('서울', '서울'), ('세종', '세종'), ('대구', '대구'), ('광주', '광주'), ('충남', '충남')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='status',
            field=models.CharField(blank=True, choices=[('나눔중', '나눔중'), ('예약중', '예약중'), ('완료', '완료')], max_length=100, null=True),
        ),
    ]
