# Generated by Django 4.1.3 on 2024-02-28 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0002_alter_question_region_alter_question_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='region',
            field=models.CharField(blank=True, choices=[('경남', '경남'), ('광주', '광주'), ('세종', '세종'), ('제주', '제주'), ('경기', '경기'), ('전북', '전북'), ('대구', '대구'), ('충북', '충북'), ('서울', '서울'), ('인천', '인천'), ('강원', '강원'), ('전남', '전남'), ('경북', '경북'), ('울산', '울산'), ('충남', '충남'), ('대전', '대전'), ('부산', '부산')], max_length=40, null=True),
        ),
    ]
