# Generated by Django 4.1.3 on 2024-02-28 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0004_alter_question_region_alter_question_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='region',
            field=models.CharField(blank=True, choices=[('전남', '전남'), ('대전', '대전'), ('세종', '세종'), ('경북', '경북'), ('경기', '경기'), ('강원', '강원'), ('전북', '전북'), ('서울', '서울'), ('광주', '광주'), ('대구', '대구'), ('울산', '울산'), ('충남', '충남'), ('부산', '부산'), ('충북', '충북'), ('경남', '경남'), ('제주', '제주'), ('인천', '인천')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='status',
            field=models.CharField(blank=True, choices=[('완료', '완료'), ('나눔중', '나눔중'), ('예약중', '예약중')], max_length=100, null=True),
        ),
    ]
